QDRANT_URL=="https://4b9203ba-777f-45ee-8a99-def751256717.europe-west3-0.gcp.cloud.qdrant.io:6333"
QDRANT_API_KEY="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2Nlc3MiOiJtIn0.mjAoAthtPZy9jZjTT0BLMy8_F-Cu8rDUUyJFRYDepj4"